### ISSUE TITLE
Article submission requirements and guidelines

### ISSUE THREAD

**Issue by csarven** [linkedresearch/info#1]
The goal is to have a snippet of text that can be used in _call for contributions_. We can improve this text through consensus. Important remarks and principles to state and strive for:
- Welcome submissions based on _native_ Web technologies. This is in contrast to (La)TeX, PDF/Word, strictly desktop or “paper user interfaces”
- Encourage self-publishing e.g., authors can give the URL to their contributions
- Provide information/URLs for applicable authoring tooling, requests for archival and persistence, and examples

This is to be a generic text which can be copy/pasted, not intended to cover or a study of all existing types of call for contributions.

**Comment by w3course** [comment]
Thanks !
[List Of Top 10 High PR Dofollow Article Submission Sites](http://webdeveloperbareilly.in/blog/seo/free-dofollow-article-submission-sites-list.html).

**Comment by csarven** [comment]
Moved to https://github.com/linkedresearch/linkedresearch.org/issues/6
