### ISSUE TITLE
Acknowledgement text for Linked Research articles

### ISSUE THREAD

**Issue by essepuntato** [linkedresearch/info#3]
It would be good to suggest authors of papers written according to the Linked Research principles to provide some sort of informative text within an Acknowledgement section at the end of the paper. Something along the lines of:

"This article was prepared following the Linked Research principles introduced at https://linkedresearch.org. In particular, it was created with [[editor]] and published in [[format]]."

Here two possible examples for the last sentence:
- "In particular, it was created with dokieli (https://dokie.li) and published in the Linked Research HTML format."
- "In particular, it was created with OpenOffice and published in RASH (https://github.com/essepuntato/rash/)."

**Comment by rhiaro** [comment]
Good idea. 

"In particular, it was created with dokieli (http://dokie.li) and published in HTML." makes more sense for that one though :)

**Comment by essepuntato** [comment]
Hi @rhiaro,

Then the structure could be reworded as follows:

"This article was prepared following the Linked Research principles introduced at https://linkedresearch.org. In particular, it was created with [[editor]] and published in HTML [[optional additional notes]]."

So as to have:

* "In particular, it was created with dokieli (https://dokie.li) and published in HTML."
* "In particular, it was created with OpenOffice and published in HTML (compliant with RASH, <a href="https://github.com/essepuntato/rash/">https://github.com/essepuntato/rash/</a>)."

What do you think?

**Comment by csarven** [comment]
I'm not sure I follow/agree with this issue. In my opinion, LR need not be used as a stamp of approval. We can't monitor the quality. There is no one-size fits all principles here for how authoring was done, or even the authoring of articles alone. Neither is it the case that articles should be in HTML or a particular format. Needless to say, there is more to it eg annotations, social engagement, interactivity..
